- hosts: terraform-ansible
  become: true
  tasks:
    - name: Criando arquivo
      copy:
        dest: /var/www/html/index.html
        content: "<h1>teste</h1>"

    - name: Habilita e reinicia o nginx via shell
      shell: |
        sudo systemctl enable nginx
        sudo systemctl restart nginx
